---
grails:
    profile: web
    codegen:
        defaultPackage: cakecatalog
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
    plugin:
      databasemigration:
        changelogFileName: 'changelog.xml'
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:


environments:
    development:
        auth:
            url: http://localhost:8008/
        dataSource:
            url: jdbc:mysql://localhost:3306/cake_catalog_monolith
            pooled: true
            jmxExport: true
            driverClassName: com.mysql.jdbc.Driver
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            username: root
            password:
    test:
        dataSource:
            url: jdbc:h2:./testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            pooled: true
            jmxExport: true
            driverClassName: org.h2.Driver
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            username: sa
            password:
    production:
        auth:
            url: https://cake-catalog-auth.herokuapp.com/
        dataSource:
            url: jdbc:postgresql://ec2-54-228-255-234.eu-west-1.compute.amazonaws.com:5432/dbq2rvsu94nh6f?user=fpkxyggrntzlax&password=e7307ff88a46bf6731e1a7c8f6a3588cf00dcce8bfd143b32a2bc170a6c516e5&sslmode=require
            driverClassName: org.postgresql.Driver
            dialect: org.hibernate.dialect.PostgreSQL94Dialect
#            username: kgmevmhljblkht
#            password: LEUEvRKfyeiNuOmUZDPshGGAqs
            pooled: true
            jmxEnabled: true